import {
  Wand2,
  MessageSquare,
  Send,
  Newspaper,
  Radar,
  BarChart3,
} from 'lucide-react';

export const MARKETING = {
  LANDING: {
    CAPABILITIES_BADGE: 'Capabilities',
    CAPABILITIES_TITLE: 'One platform, the whole loop.',
    CAPABILITIES_DESC: 'From the first onboarding question to the last analytics insight — PRESSFORGE strings every step together.',
    LOOP_BADGE: 'The loop',
    LOOP_TITLE: 'From brief to brand health, on autopilot.',
    LOOP_DESC: 'Every step feeds the next. Engagement data sharpens tomorrow\'s prompt. Mentions trigger tomorrow\'s PR pitch.',
    TRY_FLOW_BTN: 'Try the flow',
    SEE_DASHBOARD_BTN: 'See dashboard',
    PRICING_BADGE: 'Pricing',
    PRICING_TITLE: 'Simple, per-workspace.',
    GET_STARTED_BTN: 'Get started',
    MOST_POPULAR_BADGE: 'Most popular',
    FEATURES: [
      { icon: Wand2, t: "AI drafts", d: "Brand-voice aware captions, hashtags, and image briefs in seconds.", grad: "from-violet-500/30 to-fuchsia-500/10" },
      { icon: MessageSquare, t: "Telegram approvals", d: "Clients approve, edit, or reject right from their phone.", grad: "from-sky-400/30 to-blue-400/10" },
      { icon: Send, t: "Auto publishing", d: "Scheduled posts to Instagram, LinkedIn & X with zero clicks.", grad: "from-cyan-400/30 to-sky-400/10" },
      { icon: Newspaper, t: "PR distribution", d: "Targeted journalist outreach with open & reply tracking.", grad: "from-amber-400/30 to-orange-500/10" },
      { icon: Radar, t: "Brand monitoring", d: "Mentions and sentiment swept every 2 hours, alerts on negatives.", grad: "from-pink-500/30 to-rose-400/10" },
      { icon: BarChart3, t: "Learn & improve", d: "Engagement loops back into the next prompt automatically.", grad: "from-fuchsia-500/30 to-violet-500/10" },
    ],
    STEPS: [
      { n: "01", t: "Onboard the brand", d: "Voice, audience, pillars — captured in a 5-step flow." },
      { n: "02", t: "Generate & approve", d: "AI drafts → Telegram preview → one-tap approve." },
      { n: "03", t: "Publish everywhere", d: "Schedule to socials, dispatch PR, distribute pitches." },
      { n: "04", t: "Monitor & learn", d: "Mentions, sentiment, health score — fed back into next draft." },
    ],
    STATS: [
      { v: "10×", l: "Faster content turnaround" },
      { v: "92%", l: "Approval rate on first draft" },
      { v: "2 hr", l: "Brand monitoring cadence" },
      { v: "+38%", l: "Avg engagement uplift" },
    ],
    PRICING_PLANS: [
      { name: "Starter", price: "$49", tag: "For solo operators", feats: ["1 workspace", "100 AI drafts / mo", "Telegram approvals", "Basic monitoring"], highlight: false },
      { name: "Studio", price: "$199", tag: "For PR & content teams", feats: ["5 workspaces", "Unlimited drafts", "PR distribution", "Sentiment alerts", "Team roles"], highlight: true },
      { name: "Agency", price: "Custom", tag: "For agencies & enterprises", feats: ["Unlimited workspaces", "Dedicated success manager", "Custom integrations", "SSO & audit logs"], highlight: false },
    ],
  },
  HERO: {
    PRODUCT_STATS: [
      { l: "Posts published", v: "128", t: "+12%" },
      { l: "Awaiting approval", v: "4", t: "" },
      { l: "Avg engagement", v: "5.2%", t: "+0.8%" },
      { l: "Mentions / 24h", v: "37", t: "+5" },
    ],
    CHART_VALUES: [40, 55, 38, 72, 60, 82, 68, 90, 75, 95, 85, 100, 92, 110],
    TRUSTED_COMPANIES: ["NORTHWIND", "Lumen&Co", "Atlas PR", "Verso", "Helio Labs", "Quill Studio", "Northstar", "Pioneer"],
    TITLE_LINE1: "AI-powered PR & social,",
    TITLE_GRADIENT: "from brief to brand health.",
    SUBTITLE: "Onboard clients, generate on-brand content, get Telegram approvals, publish everywhere, distribute PR, and learn from every engagement — all in one continuous loop.",
    MOCK_URL: "app.pressforge.ai / dashboard",
    CHART_TITLE: "Engagement · last 14 days",
    SENTIMENT_TITLE: "Sentiment",
    HEALTH_SCORE_LABEL: "Health score",
    TELEGRAM_BADGE: "Approved on Telegram",
    GENERATED_BADGE: "Draft generated · 2.1s",
    TRUSTED_BY: "Trusted by ambitious teams",
    ONBOARD_BTN: "Start onboarding",
    DEMO_BTN: "View live dashboard demo",
  },
  CTA: {
    TITLE: "Ready to forge your ",
    TITLE_GRADIENT: "brand",
    SUBTITLE: "Spin up a workspace in under 90 seconds. No credit card required for the demo.",
    FREE_BTN: "Start free",
    TOUR_BTN: "Tour the dashboard",
  },
} as const;
