"""add_onboarding_status_and_user_profiles

Revision ID: 0379440a909a
Revises: 60290108114d
Create Date: 2026-06-30 16:07:09.176681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0379440a909a'
down_revision: Union[str, Sequence[str], None] = '60290108114d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('userId', sa.String(length=26), nullable=False),
    sa.Column('primaryGoal', sa.String(), nullable=False),
    sa.Column('contentThemes', sa.JSON(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_userId'), 'user_profiles', ['userId'], unique=True)
    op.add_column('organizations', sa.Column('teamSize', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('industries', sa.String(), nullable=True))
    
    # Add primaryGoal as nullable first, populate for existing rows, then set to NOT NULL
    op.add_column('organizations', sa.Column('primaryGoal', sa.String(), nullable=True))
    op.execute("UPDATE organizations SET \"primaryGoal\" = 'OTHER'")
    op.alter_column('organizations', 'primaryGoal', nullable=False)
    
    op.add_column('organizations', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.Text(), nullable=True))
    
    # Add onboardingStatus as nullable first, populate for existing rows, then set to NOT NULL
    op.add_column('users', sa.Column('onboardingStatus', sa.String(), nullable=True))
    op.execute("UPDATE users SET \"onboardingStatus\" = 'NOT_STARTED'")
    op.alter_column('users', 'onboardingStatus', nullable=False)
    
    op.create_index(op.f('ix_users_onboardingStatus'), 'users', ['onboardingStatus'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_onboardingStatus'), table_name='users')
    op.drop_column('users', 'onboardingStatus')
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'objective')
    op.drop_column('organizations', 'primaryGoal')
    op.drop_column('organizations', 'industries')
    op.drop_column('organizations', 'teamSize')
    op.drop_index(op.f('ix_user_profiles_userId'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
