"""create_initial_user_and_organization_related_tables

Revision ID: 60290108114d
Revises: 
Create Date: 2026-06-24 20:45:44.199494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60290108114d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('passwordHash', sa.Text(), nullable=True),
    sa.Column('accountType', sa.String(), nullable=False),
    sa.Column('profileImage', sa.Text(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('lastLogin', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('updatedAt', sa.BigInteger(), nullable=False),
    sa.Column('deletedAt', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_accountType'), 'users', ['accountType'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_isActive'), 'users', ['isActive'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ownerUserId', sa.String(length=26), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('updatedAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ownerUserId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_isActive'), 'organizations', ['isActive'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_ownerUserId'), 'organizations', ['ownerUserId'], unique=False)
    op.create_table('organization_kyc',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organizationId', sa.String(length=26), nullable=False),
    sa.Column('legalName', sa.String(), nullable=False),
    sa.Column('businessEntityType', sa.String(), nullable=False),
    sa.Column('taxIdentificationNumber', sa.String(), nullable=False),
    sa.Column('registeredAddress', sa.Text(), nullable=False),
    sa.Column('primaryContactName', sa.String(), nullable=False),
    sa.Column('primaryContactDesignation', sa.String(), nullable=True),
    sa.Column('businessDocumentFileKey', sa.String(), nullable=True),
    sa.Column('verificationStatus', sa.String(), nullable=False),
    sa.Column('verifiedAt', sa.BigInteger(), nullable=True),
    sa.Column('rejectionReason', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('updatedAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_kyc_businessEntityType'), 'organization_kyc', ['businessEntityType'], unique=False)
    op.create_index(op.f('ix_organization_kyc_id'), 'organization_kyc', ['id'], unique=False)
    op.create_index(op.f('ix_organization_kyc_legalName'), 'organization_kyc', ['legalName'], unique=False)
    op.create_index(op.f('ix_organization_kyc_organizationId'), 'organization_kyc', ['organizationId'], unique=False)
    op.create_index(op.f('ix_organization_kyc_taxIdentificationNumber'), 'organization_kyc', ['taxIdentificationNumber'], unique=False)
    op.create_index(op.f('ix_organization_kyc_verificationStatus'), 'organization_kyc', ['verificationStatus'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('organizationId', sa.String(length=26), nullable=False),
    sa.Column('userId', sa.String(length=26), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('invitedBy', sa.String(length=26), nullable=True),
    sa.Column('joinedAt', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invitedBy'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False)
    op.create_index(op.f('ix_organization_members_organizationId'), 'organization_members', ['organizationId'], unique=False)
    op.create_index(op.f('ix_organization_members_role'), 'organization_members', ['role'], unique=False)
    op.create_index(op.f('ix_organization_members_userId'), 'organization_members', ['userId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_members_userId'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_role'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organizationId'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_organization_kyc_verificationStatus'), table_name='organization_kyc')
    op.drop_index(op.f('ix_organization_kyc_taxIdentificationNumber'), table_name='organization_kyc')
    op.drop_index(op.f('ix_organization_kyc_organizationId'), table_name='organization_kyc')
    op.drop_index(op.f('ix_organization_kyc_legalName'), table_name='organization_kyc')
    op.drop_index(op.f('ix_organization_kyc_id'), table_name='organization_kyc')
    op.drop_index(op.f('ix_organization_kyc_businessEntityType'), table_name='organization_kyc')
    op.drop_table('organization_kyc')
    op.drop_index(op.f('ix_organizations_ownerUserId'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_isActive'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_users_isActive'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_accountType'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
